### PR TITLE
various small improvements

### PR DESCRIPTION
**Pull request by TheIronBorn**

### CODE REVIEW

**Comment by kpcyrd** [comment]
@TheIronBorn wow, thanks! Some of the tests are currently failing, there are multiple implementations of `setgroups` in `src/ffi/`. :)

**Comment by kpcyrd** [comment]
It seems the error on appveyor is unrelated and can be ignored, so you only need to change the function arguments in `src/ffi/linux.rs`.

**Comment by kpcyrd** [comment]
@TheIronBorn yes, thanks a lot! Do you depend on these changes? If so, I can push a new release.

**Comment by TheIronBorn** [comment]
No rush

**Pull request merged**
